"""Enhanced markdown formatter for digest output with improved structure."""
import re
from typing import List, Dict
from .news_collector import NewsStory
from .config import (ALL_JURISDICTIONS, TIER1_JURISDICTIONS,
                     TIER2_JURISDICTIONS, MAX_HEADLINE_WORDS,
                     MAX_STORY_SUMMARY)
from .date_utils import format_source_date, format_date_range


class EnhancedDigestFormatter:
    """Formats stories into enhanced markdown digest with executive summary and better structure."""

    def __init__(self, start_date, end_date):
        self.start_date = start_date
        self.end_date = end_date

    def count_words(self, text: str) -> int:
        """Count words in text."""
        return len(text.split())

    def estimate_read_time(self, word_count: int) -> int:
        """
        Estimate read time in minutes.

        Args:
            word_count: Total words

        Returns:
            Estimated minutes (assumes 250 words/minute)
        """
        return max(1, round(word_count / 250))

    def truncate_headline(self, headline: str) -> str:
        """
        Truncate headline to maximum word count.

        Args:
            headline: Original headline

        Returns:
            Truncated headline
        """
        words = headline.split()
        if len(words) <= MAX_HEADLINE_WORDS:
            return headline

        return ' '.join(words[:MAX_HEADLINE_WORDS]) + '...'

    def format_story_enhanced(self, story: NewsStory) -> str:
        """
        Format a single story with enhanced details.

        Args:
            story: NewsStory object

        Returns:
            Formatted markdown string
        """
        # Format headline
        headline = self.truncate_headline(story.title)

        # Format source and date
        source_name = story.source if story.source else 'Source'
        source_date = format_source_date(story.date)
        source_link = f"[{source_name}]({story.url})"

        # Determine story type
        story_type = self._determine_story_type(story)

        # Format summary (should be generated by LLM, but fallback to snippet)
        summary = story.summary if story.summary else story.snippet
        if not summary:
            summary = "Details available at source."

        # Clean up summary
        summary = summary.strip()
        if not summary.endswith('.'):
            summary += '.'

        # Why it matters (should be generated by LLM)
        relevance = self._get_why_it_matters(story)

        # Categories
        categories = ' '.join(f'`{cat}`' for cat in story.categories[:3])

        # Assemble story with enhanced format
        story_text = f"#### {headline}\n"
        story_text += f"**Source:** {source_link} | **Date:** {source_date}"

        if story_type:
            story_text += f" | **Type:** {story_type}"

        story_text += "\n\n"
        story_text += f"**Summary:** {summary}\n\n"
        story_text += f"**Why It Matters:** {relevance}\n\n"

        if categories:
            story_text += f"**Categories:** {categories}\n\n"

        story_text += "---\n"

        return story_text

    def _determine_story_type(self, story: NewsStory) -> str:
        """Determine story type from content."""
        text = f"{story.title} {story.summary}".lower()

        if any(term in text for term in ['court', 'ruling', 'judgment', 'decision']):
            return 'Court Decision'
        elif any(term in text for term in ['enforcement', 'fine', 'penalty', 'sanction']):
            return 'Enforcement Action'
        elif any(term in text for term in ['new law', 'legislation', 'act passed', 'bill']):
            return 'Legislation'
        elif any(term in text for term in ['regulation', 'rule', 'guidance', 'directive']):
            return 'Regulation'
        elif any(term in text for term in ['consultation', 'comment', 'feedback', 'proposal']):
            return 'Consultation'
        else:
            return 'News'

    def _get_why_it_matters(self, story: NewsStory) -> str:
        """Get why it matters statement (prefer LLM-generated if available)."""
        # Check if story has LLM-generated why it matters
        if hasattr(story, 'why_it_matters') and story.why_it_matters:
            return story.why_it_matters

        # Fallback to template-based
        return self._generate_relevance(story)

    def _generate_relevance(self, story: NewsStory) -> str:
        """Generate 'why it matters' statement (template fallback)."""
        categories = story.categories

        if not categories:
            return "Affects regulatory compliance for technology operations."

        category_impacts = {
            'AI/ML': 'Impacts AI development, deployment, and governance strategies',
            'Data Privacy': 'Affects data handling, cross-border transfers, and privacy compliance obligations',
            'Cybersecurity': 'Influences security requirements, incident response, and breach notification duties',
            'Cloud': 'Impacts cloud service agreements, vendor management, and data residency',
            'eSignature': 'Affects digital transaction validity, authentication requirements, and contract formation',
            'Contract Law': 'Shapes commercial contracting practices and terms negotiation',
            'Competition': 'Impacts market strategy, M&A activities, and platform operations',
            'Consumer Protection': 'Affects customer-facing practices, disclosures, and terms of service',
            'Corporate Governance': 'Influences board oversight, reporting duties, and ESG compliance',
            'Fintech': 'Impacts digital financial service offerings and licensing requirements',
            'AML': 'Affects transaction monitoring, customer due diligence, and reporting obligations',
            'Anti-Bribery': 'Influences compliance programs, third-party due diligence, and risk assessments',
            'Outsourcing': 'Impacts vendor contracts, service delivery models, and data sharing'
        }

        # Use first matching category
        for category in categories:
            if category in category_impacts:
                return category_impacts[category] + '.'

        return "Affects regulatory compliance for technology operations."

    def format_jurisdiction_section(self, jurisdiction: str,
                                      stories: List[NewsStory]) -> str:
        """
        Format a jurisdiction section with enhanced structure.

        Args:
            jurisdiction: Two-letter jurisdiction code
            stories: List of NewsStory objects for this jurisdiction

        Returns:
            Formatted markdown section
        """
        if not stories:
            return ""

        jur_info = ALL_JURISDICTIONS[jurisdiction]
        flag = jur_info['flag']
        name = jur_info['name']

        section = f"### {flag}  {name}\n\n"

        for story in stories:
            section += self.format_story_enhanced(story)

        return section

    def format_digest(self, selected_stories: Dict[str, List[NewsStory]],
                      insights: str = "",
                      executive_summary: str = "",
                      cross_jurisdictional_analysis: str = "") -> str:
        """
        Format complete digest with enhanced structure.

        Args:
            selected_stories: Dict mapping jurisdiction codes to stories
            insights: Region insights text (legacy)
            executive_summary: Executive summary of the week
            cross_jurisdictional_analysis: Cross-jurisdictional analysis

        Returns:
            Complete formatted markdown digest
        """
        # Calculate word count and read time
        total_words = self._calculate_word_count(
            selected_stories, insights, executive_summary, cross_jurisdictional_analysis
        )
        read_time = self.estimate_read_time(total_words)

        # Header
        date_str = format_date_range(self.start_date, self.end_date)
        digest = f"# Weekly APJ Legal & Regulatory Digest\n\n"
        digest += f"**{date_str}** | ~{total_words} words | {read_time} min read\n\n"
        digest += "---\n\n"

        # Executive Summary
        if executive_summary:
            digest += "## Executive Summary\n\n"
            digest += executive_summary + "\n\n"
            digest += "---\n\n"

        # Key Developments
        digest += "## Key Developments\n\n"

        # Tier 1 jurisdictions
        for jur_code in TIER1_JURISDICTIONS.keys():
            if jur_code in selected_stories:
                section = self.format_jurisdiction_section(
                    jur_code, selected_stories[jur_code]
                )
                digest += section

        # Tier 2 jurisdictions (grouped)
        tier2_stories = {jur: stories for jur, stories in selected_stories.items()
                         if jur in TIER2_JURISDICTIONS}

        if tier2_stories:
            digest += "### 🌏  Other APJ\n\n"
            for jur_code, stories in tier2_stories.items():
                jur_info = ALL_JURISDICTIONS[jur_code]
                flag = jur_info['flag']
                name = jur_info['name']

                digest += f"#### {flag} {name}\n\n"
                for story in stories:
                    digest += self.format_story_enhanced(story)

        # Cross-Jurisdictional Analysis
        if cross_jurisdictional_analysis:
            digest += "## Cross-Jurisdictional Analysis\n\n"
            digest += cross_jurisdictional_analysis + "\n\n"
            digest += "---\n\n"

        # Region Insights (legacy, keep for backward compatibility)
        if insights and not cross_jurisdictional_analysis:
            digest += "## 📊  Region Insights\n\n"
            digest += insights + "\n\n"

        # Footer
        digest += f"\n---\n\n"
        digest += f"*This digest covers {format_date_range(self.start_date, self.end_date)}. "
        digest += "Stories are selected based on relevance to global technology companies operating in Asia-Pacific.*\n"

        return digest

    def _calculate_word_count(self, selected_stories: Dict[str, List[NewsStory]],
                               insights: str,
                               executive_summary: str = "",
                               cross_jurisdictional_analysis: str = "") -> int:
        """Calculate total word count of digest."""
        total = 0

        # Count story words
        for stories in selected_stories.values():
            for story in stories:
                total += self.count_words(story.title)
                total += self.count_words(story.summary if story.summary else story.snippet)

                # Count why it matters
                if hasattr(story, 'why_it_matters') and story.why_it_matters:
                    total += self.count_words(story.why_it_matters)
                else:
                    total += self.count_words(self._generate_relevance(story))

        # Count executive summary
        if executive_summary:
            total += self.count_words(executive_summary)

        # Count insights words
        if insights:
            total += self.count_words(insights)

        # Count cross-jurisdictional analysis
        if cross_jurisdictional_analysis:
            total += self.count_words(cross_jurisdictional_analysis)

        return total

    def expand_acronyms_in_story(self, story: NewsStory) -> NewsStory:
        """
        Expand acronyms in story text.

        Args:
            story: NewsStory object

        Returns:
            Story with expanded acronyms
        """
        from .content_filter import ContentFilter

        filter = ContentFilter(self.start_date, self.end_date)

        # Expand in title
        story.title = filter.expand_acronyms(story.title)

        # Expand in summary
        if story.summary:
            story.summary = filter.expand_acronyms(story.summary)

        # Expand in why it matters
        if hasattr(story, 'why_it_matters') and story.why_it_matters:
            story.why_it_matters = filter.expand_acronyms(story.why_it_matters)

        return story
